// Generated by json_to_model

#import <Foundation/Foundation.h>

{% if super_name != 'NSObject' %}
#import "{{super_name}}.h"

{% endif %}

@interface {{ class_name }} : {{ super_name }}

- (id)initWithJSONData:(NSData *)data;
- (id)initWithJSONDictionary:(NSDictionary *)dictionary;
- (NSDictionary *)JSONDictionary;
- (NSData *)JSONData;

{% for property in properties %}
@property (nonatomic, {{ property.retain_type }}) {{ property.type }} {{ property.name }};
{% endfor %}

@end


