// Generated by json_to_model

#import <Foundation/Foundation.h>
#import "Post.h"


@interface Reply : Post

- (id)initWithJSONData:(NSData *)data;
- (id)initWithJSONDictionary:(NSDictionary *)dictionary;
- (NSDictionary *)JSONDictionary;
- (NSData *)JSONData;


@property (nonatomic, assign) NSInteger toId;


@end

