// Generated by json_to_model

#import <Foundation/Foundation.h>


@interface User : NSObject

- (id)initWithJSONData:(NSData *)data;
- (id)initWithJSONDictionary:(NSDictionary *)dictionary;
- (NSDictionary *)JSONDictionary;
- (NSData *)JSONData;


@property (nonatomic, copy) NSString * username;

@property (nonatomic, assign) NSInteger age;

@property (nonatomic, assign) BOOL registered;

@property (nonatomic, copy) NSString * email;


@end

