// Generated by json_to_model

import Foundation

class Reply : Post {

    
    var toId : Int = 0
    


    override init(JSONDictionary: NSDictionary) {
        super.init(JSONDictionary: JSONDictionary)

 
        if (!(JSONDictionary["to_id"] is NSNull)) {
            self.toId = JSONDictionary["to_id"]!.integerValue
        }
 
    }

    convenience init?(JSONData: NSData) {
        var error : NSErrorPointer = nil
        var result : NSDictionary? = NSJSONSerialization.JSONObjectWithData(JSONData, options:NSJSONReadingOptions.AllowFragments, error:error) as NSDictionary?
        if (result != nil) {
            self.init(JSONDictionary:result!)
        } else {
            self.init(JSONDictionary:NSMutableDictionary())
            return nil
        }
    }


    override func JSONDictionary() -> NSDictionary {


        var dictionary : NSMutableDictionary = super.JSONDictionary() as NSMutableDictionary

 
        dictionary["to_id"] = self.toId
 
        return dictionary;
    }

    override func JSONData() -> NSData? {

        var error : NSErrorPointer = nil
        var data : NSData? = NSJSONSerialization.dataWithJSONObject(self.JSONDictionary(), options:nil, error:error)
        if (error != nil) {
            return nil
        }
        return data
    }

}